let chapters = JSON.parse(localStorage.getItem('checkcar-chapters')||'null') || [
['准备','提车前准备','预约白天、自然光下验车；提前 1–2 小时到店，带好手机手电筒、身份证、驾驶证、订单和付款凭证。',[['p.1','时间与工具','预约白天室外自然光，预留充足时间；手机手电筒检查车漆和缝隙，手机全程录像留证。',0,'confirm'],['p.2','材料与交付准备','带身份证原件、驾驶证、购车合同/订单确认单、付款凭证；提前确认车辆已洗净且电量 80% 以上。',0,'confirm']]],
['第一章','核对车辆基础信息','先核实 VIN、生产日期和里程，异常时先沟通，不要进入签字流程。',[['1.1','VIN 码三码合一','前挡左下角、副驾 B 柱铭牌、购车合同/合格证上的 17 位 VIN 必须完全一致。',1,'record'],['1.2','生产日期','查看 B 柱铭牌出厂日期；一般 3 个月内为新车，超过 6 个月按库存车协商补偿或换车。',1,'record'],['1.3','表显里程','新车合理里程一般为 0–50 km；里程过高需警惕展车或试驾车。',1,'record']]],
['第二章','玻璃与轮胎日期核验（防运损）','所有玻璃和轮胎日期都必须早于整车出厂日期。',[['2.1','全车玻璃日期','逐块检查“数字+黑点”日期码：点在数字前为 7 减点数，点在数字后为 13 减点数；任一玻璃晚于整车出厂日期，大概率为运损后更换。',1,'record'],['2.2','轮胎日期与状态','DOT 码后 4 位为周+年（如 2525 为 2025 年第 25 周）；四条日期应接近且早于整车，检查胎毛、鼓包、裂纹和卡石子。',1,'record']]],
['第三章','外观漆面与细节检查','在自然光下绕车 3 圈，用手电筒 45° 斜照重点部位。',[['3.1','漆面检查','重点查前后保险杠、门把手、轮眉、侧裙、后视镜和腰线：无划痕、凹坑、色差、飞漆或橘皮纹。',0,'photo'],['3.2','缝隙与开合','车门、引擎盖、后备箱缝隙左右均匀对称；反复开关，铰链无异响。',1,'photo'],['3.3','轮毂检查','蹲下用手电斜照轮毂边缘和内侧，无运输刮花、磕碰或变形。',0,'photo'],['3.4','全车灯光','依次测试近远光、转向、前后雾灯、刹车、倒车和双闪；灯罩无划痕，内部不起雾。',0,'photo']]],
['第四章','内饰与车机功能实测','每项当场实测，问题拍照或录像留证。',[['4.1','座椅与内饰','Nappa 真皮座椅无污渍、褶皱、破损，缝线工整；测试主副驾电动调节、零重力、加热、通风、按摩及异响。',0,'photo'],['4.2','中控屏幕','让小爱同学开启屏幕清洁模式，在纯白背景检查坏点、亮点、漏光；触控滑动和分屏流畅无卡顿。',1,'photo'],['4.3','空调与音响','最低温测制冷、最高温测制热，无刺鼻异味；播放音乐检查全车扬声器无杂音、破音。',0,'photo'],['4.4','车窗与天窗','四门一键升降顺畅、无抖动异响；检查天幕玻璃无划痕、砂眼。',0,'photo'],['4.5','语音与互联','连续唤醒小爱同学，响应灵敏；测试 NFC 钥匙和 App 远程控车。',0,'photo']]],
['第五章','选装配置专属验车重点','按订单选装配置逐项核对和实测。',[['5.1','25 扬声器：低音炮','打开后备箱，检查两侧或底部已安装原厂低音炮扬声器。',0,'confirm'],['5.2','25 扬声器：全车排雷与音效','播放高低音和环绕测试音乐，音量 20–30，确认 25 个扬声器均有声音、无电流声/破音/杂音；切换全景声等模式，声场切换顺畅。',0,'confirm'],['5.3','科技舒享包：电动吸合门','轻推车门，电机吸合顺畅安静、无异响。',0,'confirm'],['5.4','科技舒享包：零重力座椅','开启零重力模式，观察腿托和靠背调整平滑、无卡顿。',0,'confirm'],['5.5','科技舒享包：方向盘电动调节','测试方向盘上下、前后电动调节及记忆功能灵敏。',0,'confirm'],['5.6','科技舒享包：外后视镜','强光下观察自动防眩目，测试电动折叠顺畅。',0,'confirm']]],
['第六章','底盘、三电与外部接口','优先请门店举升；无法举升时用手机手电筒检查底盘。',[['6.1','底盘与电池包','检查电池包外壳无磕碰、刮擦、变形或渗漏痕迹。',1,'record'],['6.2','充电口','充电口盖开合顺畅，接口内无异物或烧蚀痕迹。',0,'confirm'],['6.3','雨刮与玻璃水','测试雨刮各档位和喷水雾化效果。',0,'confirm']]],
['第七章','随车物品与手续清点','清点完成并确认保险生效后，再进入签字环节。',[['7.1','随车工具','清点三角警示牌、反光背心、拖车钩、补胎工具/充气泵及原厂赠品。',0,'confirm'],['7.2','车钥匙','确认 2 张 NFC 卡片钥匙和实体钥匙齐全，当场测试解锁、锁车。',0,'confirm'],['7.3','行车记录仪','确认已插好 U 盘，并测试成像清晰。',0,'confirm'],['7.4','必收文件','清点购车发票、车辆合格证原件、车辆一致性证书、三包凭证、保养手册、保险单和临时牌照。',1,'record']]],
['注意','核心避坑与注意事项','以下原则确认无误后，才签字提车。',[['t.1','先验车，后签字','所有检查确认无误后，再付尾款或签交付单。',1,'confirm'],['t.2','玻璃划痕拒绝抛光','发现玻璃浅划痕，拒绝抛光打磨；要求无痕修复或换车。',1,'confirm'],['t.3','保险生效时间','确认商业险和交强险提车当天或更早生效，避免脱险上路。',1,'confirm'],['t.4','先上牌，后贴膜','完成车管所验车上牌后，再贴车衣或改色膜。',0,'confirm']]]
].map(([no,title,intro,items])=>({id:crypto.randomUUID(),no,title,intro,items:items.map(([id,title,desc,veto,mode])=>({id,title,desc,veto:!!veto,mode}))}));
const state=JSON.parse(localStorage.getItem('checkcar-state')||'{}'), statuses=state.statuses||{}, notes=state.notes||{}, records=state.records||{}, photos={}; let open=new Set(JSON.parse(localStorage.getItem('checkcar-open')||'["第一章"]')), editTarget=null;
const fieldMap={'1.1':['VIN 码'],'1.2':['铭牌生产日期'],'1.3':['仪表里程（公里）'],'2.1':['前挡日期','左前门日期','右前门日期','左后门日期','右后门日期','后挡日期'],'2.2':['左前 DOT','右前 DOT','左后 DOT','右后 DOT'],'6.1':['电池健康度 / 循环次数'],'7.4':['发现问题及处理结果','交付专员姓名 / 电话','验车日期']};
function save(){localStorage.setItem('checkcar-state',JSON.stringify({statuses,notes,records}));localStorage.setItem('checkcar-open',JSON.stringify([...open]));localStorage.setItem('checkcar-chapters',JSON.stringify(chapters));}
function all(){return chapters.flatMap(c=>c.items)}
function render(){const items=all(), done=items.filter(i=>statuses[i.id]).length, pass=Object.values(statuses).filter(x=>x==='pass').length,fail=Object.values(statuses).filter(x=>x==='fail').length,skip=Object.values(statuses).filter(x=>x==='skip').length,veto=items.filter(i=>i.veto&&statuses[i.id]==='fail').length; document.querySelector('#hero-meta').textContent=`${items.length} 项检查 · ${items.filter(i=>i.veto).length} 项一票否决`;document.querySelector('#progress-percent').textContent=`${Math.round(done/items.length*100)}%`;document.querySelector('#progress-bar').style.width=`${done/items.length*100}%`;document.querySelector('#stats').innerHTML=[['green','合格',pass],['orange','异常',fail],['blue','跳过',skip],['red','否决异常',veto]].map(x=>`<div class="stat ${x[0]}"><b>${x[2]}</b><span>${x[1]}</span></div>`).join('');document.querySelector('#chapters').innerHTML=chapters.map((c,ci)=>{const complete=c.items.filter(i=>statuses[i.id]).length,progress=c.items.length?complete/c.items.length*100:0;return `<section class="chapter" draggable="true" data-chapter="${c.id}"><div class="chapter-head" data-open="${c.no}"><span class="chapter-no">${String(ci+1).padStart(2,'0')}</span><span class="chapter-title">${c.title}</span><span class="chapter-count" style="--chapter-progress:${progress}%">${complete}/${c.items.length}</span><span class="sort-hint">☷</span><button class="swipe-delete" data-delete-chapter="${c.id}">删除</button><span>${open.has(c.no)?'⌃':'⌄'}</span></div>${open.has(c.no)?`<p class="chapter-intro">${c.intro}</p><div class="items">${c.items.map((i,ii)=>itemHTML(i,ii)).join('')}</div><button class="add-item ghost" data-add-item="${c.id}">＋ 新增验车项</button>`:''}</section>`}).join(''); bind(); updateReport(); enableSorting();}
function dateTool(id){const names=id==='2.1'?['前挡','左前门','右前门','左后门','右后门','后挡']:id==='2.2'?['左前轮胎','右前轮胎','左后轮胎','右后轮胎']:[];return names.length?`<div class="date-list">${names.map((n,i)=>`<div class="date-entry"><span class="date-label">${n}</span><button class="date-button" data-date-id="${id}" data-date-index="${i}">◷</button><small class="date-preview">${records[`date:${id}:${i}`]||'未录入'}</small></div>`).join('')}</div>`:''}
function itemHTML(i,ii){const st=statuses[i.id], photoCount=(photos[i.id]||[]).length, canPhoto=['photo','record'].includes(i.mode); return `<article class="item" draggable="true" data-item="${i.id}"><div class="item-top"><span class="item-index">${ii+1}</span><h3>${i.title}</h3>${i.veto?'<span class="badge">否决项</span>':''}<div class="item-tools"><button class="icon-btn edit" data-id="${i.id}">⋯</button><span class="sort-hint">☷</span></div><button class="swipe-delete" data-delete-item="${i.id}">删除</button></div><p class="item-desc">${i.desc}</p>${canPhoto?`<div class="photos"><button class="photo-btn camera" data-id="${i.id}">▣ 拍照${photoCount?' +'+photoCount:''}</button>${(photos[i.id]||[]).map(src=>`<img src="${src}">`).join('')}</div>`:''}${dateTool(i.id)}${fieldMap[i.id]&&!['2.1','2.2'].includes(i.id)?`<div class="record">${fieldMap[i.id].map(f=>`<label>${f}<input data-record="${i.id}:${f}" value="${records[i.id+':'+f]||''}"></label>`).join('')}</div>`:''}<div class="item-actions">${[['pass','✓ 合格'],['fail','! 异常'],['skip','→ 跳过']].map(([k,t])=>`<button class="action ${k} ${st===k?'active':''}" data-status="${k}" data-id="${i.id}">${t}</button>`).join('')}</div>${st==='fail'?`<input class="note" data-note="${i.id}" placeholder="异常备注（可选）" value="${notes[i.id]||''}">`:''}</article>`}
function bind(){document.querySelectorAll('.chapter-head').forEach(x=>x.onclick=e=>{if(e.target.closest('.sort-hint,.chapter-menu'))return;open.has(x.dataset.open)?open.delete(x.dataset.open):open.add(x.dataset.open);save();render()});document.querySelectorAll('[data-status]').forEach(x=>x.onclick=()=>{statuses[x.dataset.id]=statuses[x.dataset.id]===x.dataset.status?undefined:x.dataset.status;if(!statuses[x.dataset.id])delete statuses[x.dataset.id];save();render()});document.querySelectorAll('[data-note]').forEach(x=>x.oninput=()=>{notes[x.dataset.note]=x.value;save()});document.querySelectorAll('[data-record]').forEach(x=>x.oninput=()=>{records[x.dataset.record]=x.value;save()});document.querySelectorAll('.camera').forEach(x=>x.onclick=()=>{document.querySelector('#camera-input').dataset.id=x.dataset.id;document.querySelector('#camera-input').click()});document.querySelectorAll('.edit').forEach(x=>x.onclick=e=>{e.stopPropagation();openEdit(x.dataset.id)});document.querySelectorAll('[data-add-item]').forEach(x=>x.onclick=()=>{const c=chapters.find(c=>c.id===x.dataset.addItem);if(c){c.items.push({id:crypto.randomUUID(),title:'新验车项',desc:'填写检查说明',veto:false,mode:'confirm'});save();render()}});document.querySelectorAll('[data-chapter-menu]').forEach(x=>x.onclick=e=>{e.stopPropagation();if(confirm('删除此章节及其中验车项？')){const c=chapters.find(c=>c.id===x.dataset.chapterMenu);c?.items.forEach(i=>{delete statuses[i.id];delete notes[i.id]});chapters.splice(chapters.indexOf(c),1);save();render()}});document.querySelectorAll('[data-delete-item]').forEach(b=>b.onclick=e=>{e.stopPropagation();if(confirm('删除此验车项？')){for(const c of chapters)c.items=c.items.filter(i=>i.id!==b.dataset.deleteItem);delete statuses[b.dataset.deleteItem];delete notes[b.dataset.deleteItem];save();render()}});document.querySelectorAll('[data-delete-chapter]').forEach(b=>b.onclick=e=>{e.stopPropagation();if(confirm('删除此章节及其中验车项？')){const c=chapters.find(c=>c.id===b.dataset.deleteChapter);c?.items.forEach(i=>{delete statuses[i.id];delete notes[i.id]});chapters.splice(chapters.indexOf(c),1);save();render()}})}
function openEdit(id){const i=all().find(x=>x.id===id);editTarget=i;document.querySelector('#edit-name').value=i.title;document.querySelector('#edit-desc').value=i.desc;document.querySelector('#edit-veto').checked=i.veto;document.querySelector('#edit-dialog').showModal()}
document.querySelector('#edit-form').onsubmit=e=>{e.preventDefault();if(editTarget){editTarget.title=document.querySelector('#edit-name').value;editTarget.desc=document.querySelector('#edit-desc').value;editTarget.veto=document.querySelector('#edit-veto').checked;document.querySelector('#edit-dialog').close();render()}};
document.querySelector('#camera-input').onchange=async e=>{const file=e.target.files[0],id=e.target.dataset.id;if(!file)return;const db=await openDB();await new Promise((res,rej)=>{const tx=db.transaction('photos','readwrite');tx.objectStore('photos').add({id,blob:file});tx.oncomplete=res;tx.onerror=rej});const src=URL.createObjectURL(file);(photos[id]??=[]).push(src);render();e.target.value=''};
function openDB(){return new Promise((res,rej)=>{const r=indexedDB.open('checkcar-db',1);r.onupgradeneeded=()=>r.result.createObjectStore('photos',{autoIncrement:true});r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)})}
function updateReport(){const items=all(),p=Object.values(statuses).filter(x=>x==='pass').length,f=Object.values(statuses).filter(x=>x==='fail').length,s=Object.values(statuses).filter(x=>x==='skip').length;document.querySelector('#report').textContent=`【小米 YU7 Pro 提车验车报告】\n进度：${Object.keys(statuses).length}/${items.length}（合格 ${p} / 异常 ${f} / 跳过 ${s}）\n\n`+items.map(i=>`${statuses[i.id]==='pass'?'✓':statuses[i.id]==='fail'?'✗':statuses[i.id]==='skip'?'—':'□'} ${i.id} ${i.title}${notes[i.id]?` 备注：${notes[i.id]}`:''}`).join('\n')}
document.querySelectorAll('.tab').forEach(t=>t.onclick=()=>{document.querySelectorAll('.tab').forEach(x=>x.classList.toggle('active',x===t));document.querySelector('#inspection-page').classList.toggle('hidden',t.dataset.tab!=='inspection');document.querySelector('#report-page').classList.toggle('hidden',t.dataset.tab!=='report')});document.querySelector('#generate').onclick=()=>{document.querySelector('[data-tab=report]').click()};document.querySelector('#copy-report').onclick=()=>navigator.clipboard?.writeText(document.querySelector('#report').textContent);document.querySelector('#reset').onclick=()=>{if(confirm('确定清除所有验车记录？')){localStorage.removeItem('checkcar-state');location.reload()}};document.querySelector('#add-chapter').onclick=()=>{chapters.push({id:crypto.randomUUID(),no:'自定义',title:'新验车章节',intro:'填写章节说明',items:[]});save();render()};
async function loadPhotos(){const db=await openDB();const rows=await new Promise((res,rej)=>{const r=db.transaction('photos').objectStore('photos').getAll();r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)});for(const row of rows){photos[row.id]??=[];photos[row.id].push(URL.createObjectURL(row.blob))}render()}
render();loadPhotos();

// 日期码辅助：DOT 周码与玻璃年月码会即时显示标准日期。
function decodeDate(value, kind){const s=value.trim();if(kind==='dot'){const m=s.match(/(\d{2})(\d{2})$/);if(!m)return '';const d=new Date(2000+Number(m[2]),0,1+Number(m[1])*7-1);return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`}const m=s.match(/(\d{4})[\s./-]?(\d{1,2})[\s./-]?(\d{1,2})?/);return m?`${m[1]}-${String(m[2]).padStart(2,'0')}${m[3]?`-${String(m[3]).padStart(2,'0')}`:''}`:''}
function refreshDates(){document.querySelectorAll('[data-record]').forEach(input=>{const [id]=input.dataset.record.split(':');let out=input.nextElementSibling;if(!out)return;out.textContent=id==='2.2'?decodeDate(input.value,'dot'):id==='2.1'?decodeDate(input.value,'glass'):''})}
document.addEventListener('input',refreshDates);refreshDates();
document.addEventListener('click',e=>{if(e.target.closest('.sort-hint'))e.stopPropagation()},true);
document.querySelectorAll('.sort-hint').forEach(x=>x.textContent='☷');
document.addEventListener('input',e=>{if(!e.target.matches('[data-tool]'))return;const [id,n,key]=e.target.dataset.tool.split(':');const value=e.target.value;records[`${id}:${n}:${key}`]=value;save();const out=document.querySelector(`[data-tool-out="${id}:${n}"]`);if(id==='2.2'){const m=value.match(/(\d{2})(\d{2})$/);out.textContent=m?`${2000+ +m[2]} 年第 ${m[1]} 周（DOT ${value}）`:''}else{const s=value.replace(/\s/g,''),m=s.match(/(\d)([•.·]*)$|^([•.·]*)(\d)/);if(m){const year=2020+ +(m[1]||m[3]),dots=(m[2]||m[4]||'').length,month=m[2]?7-dots:13-dots;out.textContent=month>0&&month<13?`${year} 年 ${month} 月（日期码）`:''}}});
document.addEventListener('change',e=>{if(!e.target.matches('[data-tool]'))return;const [id,n,key]=e.target.dataset.tool.split(':');records[`${id}:${n}:${key}`]=e.target.value;save();if(id==='2.1'){const y=records[`${id}:${n}:year`],b=records[`${id}:${n}:before`],a=records[`${id}:${n}:after`],dots=b!==undefined&&b!==''?+b:+a;const month=b!==undefined&&b!==''?7-dots:13-dots;document.querySelector(`[data-tool-out="${id}:${n}"]`).textContent=y&&month>0&&month<13?`${2020+ +y} 年 ${month} 月（日期码）`:''}});
function enableSorting(){document.querySelectorAll('.sort-hint').forEach(handle=>{let timer,dragging;handle.addEventListener('pointerdown',e=>{e.stopPropagation();const card=handle.closest('.item,.chapter');timer=setTimeout(()=>{dragging=card;dragging.classList.add('sorting');handle.setPointerCapture?.(e.pointerId)},380)});handle.addEventListener('pointermove',e=>{if(!dragging)return;const target=document.elementFromPoint(e.clientX,e.clientY)?.closest(dragging.classList.contains('item')?'.item':'.chapter');if(!target||target===dragging)return;if(dragging.classList.contains('item')){const from=chapters.find(c=>c.items.some(i=>i.id===dragging.dataset.item)),to=chapters.find(c=>c.items.some(i=>i.id===target.dataset.item));if(!from||from!==to)return;const a=from.items.findIndex(i=>i.id===dragging.dataset.item),b=from.items.findIndex(i=>i.id===target.dataset.item);[from.items[a],from.items[b]]=[from.items[b],from.items[a]]}else{const a=chapters.findIndex(c=>c.id===dragging.dataset.chapter),b=chapters.findIndex(c=>c.id===target.dataset.chapter);[chapters[a],chapters[b]]=[chapters[b],chapters[a]]}target.parentElement.insertBefore(dragging,target);save()});const end=()=>{clearTimeout(timer);if(dragging){dragging.classList.remove('sorting');dragging=null}};handle.addEventListener('pointerup',end);handle.addEventListener('pointercancel',end)})}
async function photoParts(){const db=await openDB(),rows=await new Promise((res,rej)=>{const r=db.transaction('photos').objectStore('photos').getAll();r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)}),parts=[];for(const row of rows){const item=all().find(i=>i.id===row.id);if(!item)continue;const base64=await new Promise((res,rej)=>{const fr=new FileReader();fr.onload=()=>res(String(fr.result).split(',')[1]);fr.onerror=rej;fr.readAsDataURL(row.blob)});parts.push({label:`${item.id} ${item.title}`,base64})}return parts}
function reportPayload(){return {vehicle:'小米 YU7 Pro',summary:{total:all().length,completed:Object.keys(statuses).length,pass:Object.values(statuses).filter(x=>x==='pass').length,fail:Object.values(statuses).filter(x=>x==='fail').length,skip:Object.values(statuses).filter(x=>x==='skip').length},records,items:all().map(i=>({id:i.id,title:i.title,description:i.desc,status:statuses[i.id]||'unmarked',note:notes[i.id]||''}))}}
if(document.querySelector('#ai-dialog')){document.querySelector('#generate').onclick=()=>document.querySelector('#ai-dialog').showModal();document.querySelector('#ai-cancel').onclick=()=>document.querySelector('#ai-dialog').close();document.querySelector('#ai-form').onsubmit=async e=>{e.preventDefault();const key=document.querySelector('#ai-key').value.trim();if(!key){document.querySelector('#ai-error').textContent='请输入 API Key';return}try{document.querySelector('#ai-error').textContent='正在读取照片并生成…';const content=[{type:'text',text:`请基于完整验车 JSON 和照片生成中文专业、客观的验车报告。必须包含风险分级、待处理事项和照片证据说明；不要臆测无法确认的内容。\n\n验车原始数据（JSON）：\n${JSON.stringify(reportPayload(),null,2)}`}];for(const image of await photoParts()){content.push({type:'text',text:`照片证据：${image.label}`},{type:'image_url',image_url:{url:`data:image/jpeg;base64,${image.base64}`}})}const r=await fetch(document.querySelector('#ai-endpoint').value,{method:'POST',headers:{'Content-Type':'application/json','Authorization':`Bearer ${key}`},body:JSON.stringify({model:document.querySelector('#ai-model').value,messages:[{role:'user',content}]})});if(!r.ok)throw Error(`AI 接口请求失败（HTTP ${r.status}）`);const j=await r.json();document.querySelector('#report').textContent=j.output_text||j.choices?.[0]?.message?.content||JSON.stringify(j,null,2);document.querySelector('#ai-dialog').close();document.querySelector('[data-tab=report]').click()}catch(err){document.querySelector('#ai-error').textContent=err.message}}}
let editingDate,editingDateIndex=0;function dotMonth(year,week){const d=new Date(year,0,4),day=d.getDay()||7;d.setDate(d.getDate()-day+1+(week-1)*7);return d.getMonth()+1}function openDateDialog(id,index=0){editingDate=id;editingDateIndex=index;const glass=id==='2.1',n=glass?['前挡','左前门','右前门','左后门','右后门','后挡'][index]:['左前轮胎','右前轮胎','左后轮胎','右后轮胎'][index];document.querySelector('#date-title').textContent=`${n} ${glass?'玻璃日期码':'轮胎 DOT 日期码'}`;document.querySelector('#date-fields').innerHTML=glass?`<label>${n}<select data-date="before"><option value="">前黑点</option>${[0,1,2,3,4,5,6].map(x=>`<option>${x}</option>`).join('')}</select><select data-date="year"><option value="">年份末位</option>${[0,1,2,3,4,5,6,7,8,9].map(x=>`<option>${x}</option>`).join('')}</select><select data-date="after"><option value="">后黑点</option>${[0,1,2,3,4,5,6].map(x=>`<option>${x}</option>`).join('')}</select></label>`:`<label>${n}<input data-date="dot" inputmode="numeric" maxlength="4" placeholder="2525"></label>`;document.querySelectorAll('[data-date]').forEach(x=>x.value=records[`datepart:${id}:${index}:${x.dataset.date}`]||'');document.querySelector('#date-dialog').showModal()}document.addEventListener('click',e=>{const b=e.target.closest('[data-date-id]');if(b)openDateDialog(b.dataset.dateId,+b.dataset.dateIndex||0)});document.querySelector('#date-form').onsubmit=e=>{e.preventDefault();const glass=editingDate==='2.1',values=[...document.querySelectorAll('[data-date]')],get=k=>values.find(x=>x.dataset.date===k)?.value||'';values.forEach(x=>records[`datepart:${editingDate}:${editingDateIndex}:${x.dataset.date}`]=x.value);let result='未录入';if(glass){const b=get('before'),y=get('year'),a=get('after'),m=b!==''?7-+b:a!==''?13-+a:0;if(y&&m>0&&m<13)result=`${2020+ +y}年${m}月`}else{const m=get('dot').match(/(\d{2})(\d{2})$/);if(m){const year=2000+ +m[2],week=+m[1];result=`${year}年${dotMonth(year,week)}月 · 第${m[1]}周`}}records[`date:${editingDate}:${editingDateIndex}`]=result;save();document.querySelector('#date-dialog').close();render()}
// 手柄专属排序：同级元素才可换位；验车项的父容器不同即不会排序。
let activeSort, sortTimer;
enableSorting=function(){if(enableSorting.ready)return;enableSorting.ready=true;document.addEventListener('pointerdown',e=>{const handle=e.target.closest('.sort-hint');if(!handle)return;e.preventDefault();e.stopImmediatePropagation();const card=handle.closest('.item,.chapter');sortTimer=setTimeout(()=>{activeSort={card,parent:card.parentElement};card.classList.add('sorting');card.parentElement.classList.add('sorting-list');handle.setPointerCapture?.(e.pointerId)},360)},true);document.addEventListener('pointermove',e=>{if(!activeSort)return;const {card,parent}=activeSort,target=document.elementFromPoint(e.clientX,e.clientY)?.closest(card.classList.contains('item')?'.item':'.chapter');if(!target||target===card||target.parentElement!==parent)return;const before=target.getBoundingClientRect(),drag=card.getBoundingClientRect();if(card.classList.contains('item')){const chapter=chapters.find(c=>c.items.some(i=>i.id===card.dataset.item));const a=chapter?.items.findIndex(i=>i.id===card.dataset.item),b=chapter?.items.findIndex(i=>i.id===target.dataset.item);if(a<0||b<0)return;[chapter.items[a],chapter.items[b]]=[chapter.items[b],chapter.items[a]]}else{const a=chapters.findIndex(c=>c.id===card.dataset.chapter),b=chapters.findIndex(c=>c.id===target.dataset.chapter);if(a<0||b<0)return;[chapters[a],chapters[b]]=[chapters[b],chapters[a]]}parent.insertBefore(card,card.compareDocumentPosition(target)&Node.DOCUMENT_POSITION_FOLLOWING?target.nextSibling:target);const after=target.getBoundingClientRect();target.animate([{transform:`translateY(${before.top-after.top}px)`},{transform:'translateY(0)'}],{duration:520,easing:'cubic-bezier(.22,1.18,.36,1)'});card.animate([{transform:`translateY(${drag.top-card.getBoundingClientRect().top}px)`},{transform:'translateY(0)'}],{duration:520,easing:'cubic-bezier(.22,1.18,.36,1)'});save()},true);const end=()=>{clearTimeout(sortTimer);if(!activeSort)return;activeSort.card.classList.remove('sorting');activeSort.parent.classList.remove('sorting-list');activeSort=undefined;render()};document.addEventListener('pointerup',end,true);document.addEventListener('pointercancel',end,true)};
enableSorting();
document.addEventListener('pointerdown',e=>{const card=e.target.closest('.item,.chapter');if(!card||e.target.closest('button,input,select,textarea,.sort-hint'))return;card.dataset.swipeX=e.clientX;card.dataset.swipeY=e.clientY});document.addEventListener('pointerup',e=>{const card=e.target.closest('.item,.chapter');if(!card||card.dataset.swipeX===undefined)return;const dx=e.clientX-+card.dataset.swipeX,dy=e.clientY-+card.dataset.swipeY;delete card.dataset.swipeX;delete card.dataset.swipeY;if(dx<-55&&Math.abs(dy)<35)card.classList.add('swiped');else if(dx>20)card.classList.remove('swiped')});
